name: Docker Image CI

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.13.0
      
      - name: Install dependencies
        run: npm ci

      - name: Run lint test
        run: npx eslint .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        run: docker build -t horvathv01/bike-service-project:bike-service-web-app .

      - name: Push docker image
        run: docker push horvathv01/bike-service-project:bike-service-web-app

      - name: Run application in Docker container
        run: docker run -d -p 8080:8080 horvathv01/bike-service-project:bike-service-web-app
