name: Docker Image CI

on:
  push:
    branches:
      - main
      - workflow_dockerize
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.13.0
      
      - name: Install dependencies
        run: npm ci

      - name: Run lint test
        run: npx eslint .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag
        id: set_image_tag
        run: echo "::set-output name=tag::$(date +'%Y%m%d-%H%M%S')"

      - name: Build docker image
        run: docker build -t krisztanzero/bike-service-project:bike-service-web-app-${{ steps.set_image_tag.outputs.tag }} .

      - name: Push docker image
        run: docker push krisztanzero/bike-service-project:bike-service-web-app-${{ steps.set_image_tag.outputs.tag }}
